### PR TITLE
dagre.layout minor performance optimization

### PR DESCRIPTION
**Pull request by beru**
I've confirmed that this minor performance optimization reduces 5-10% of `dagre.layout` time with [net.pbtxt](https://github.com/lutzroeder/netron/issues/223#issue-403671947) model.

### CODE REVIEW

**Comment by lutzroeder** [comment]
@beru are these improvements visible when running `npm run test measure` and summing up the `render` column?

**Comment by beru** [comment]
@lutzroeder I see small reduction.

commit | render column sum
-------|-----------
9c9d2f9c7ac6fbf9caaee394d46a4d987d6d3911 | 85.775482977
179f4f2a48eeb5b052a07eaacf4570c676ba505b | 87.357818822

[measures_9c9d2f9c7ac6fbf9caaee394d46a4d987d6d3911.csv](https://github.com/user-attachments/files/15845965/measures_9c9d2f9c7ac6fbf9caaee394d46a4d987d6d3911.csv)

[measures_179f4f2a48eeb5b052a07eaacf4570c676ba505b.csv](https://github.com/user-attachments/files/15845966/measures_179f4f2a48eeb5b052a07eaacf4570c676ba505b.csv)

I needed to remove the following lines from `test/models.json` file for the measurement.

<details><summary>removed lines</summary>

```
  {
    "type":     "coreml",
    "target":   "SqueezeNet.mlmodel",
    "source":   "https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNet.mlmodel",
    "format":   "Core ML v1",
    "link":     "https://developer.apple.com/machine-learning/models"
  },
  {
    "type":     "coreml",
    "target":   "SqueezeNetFP16.mlmodel",
    "source":   "https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNetFP16.mlmodel",
    "format":   "Core ML v2",
    "link":     "https://developer.apple.com/machine-learning/models"
  },
  {
    "type":     "coreml",
    "target":   "SqueezeNetInt8LUT.mlmodel",
    "source":   "https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNetInt8LUT.mlmodel",
    "format":   "Core ML v3",
    "tags":     "quantization",
    "link":     "https://developer.apple.com/machine-learning/models"
  },
```

</details>

**Comment by lutzroeder** [comment]
> I needed to remove the following lines from test/models.json file for the measurement.

Can you explain why these files needed to be removed?

**Comment by beru** [comment]
> Can you explain why these files needed to be removed?

Because I see `Error: 403` response. Here's the output of `npm run test measure` at my side whe the lines are present.

<details><summary>output</summary>

```
beru@beru-System-Product-Name:~/projects/netron$ npm run test measure
_/boolean.onnx
_/cnn_classifier.h5
_/config.json
_/config.pbtxt
_/coreml_invalid_file.mlmodel
_/empty.zip
_/haarcascade_mcs_nose.xml
_/imagenet_2012_challenge_label_map_proto.pbtxt
_/keras2onnx.onnx
_/knift_index.pb
_/labelmap.pbtxt
_/gzip_invalid_archive.tar.gz
_/gzip_invalid_compression.tar.gz
_/invalid_git_lfs.mlmodel
_/invalid_html.mlmodel.zip
_/invalid_html.tflite
_/onnx-metadata.json
_/ops.pbtxt
_/python-import.pt
_/python-from-import.pt
_/random.onnx
_/tflite.onnx
_/vk_swiftshader_icd.json
_/yolo-1c.meta
_/zip_invalid_archive.zip
acuity/inception_v1.json
armnn/simple_network.armnn
armnn/ssd_mobilenet_v1.armnn
armnn/ssd_mobilenet_v3_small_coco_2019_08_14_q8.armnn
armnn/ssd_mobilenet_v3_small_coco_2019_08_14_q8.json
armnn/ssd_mobilenet_v3_small_coco_2019_08_14_q16.armnn
barracuda/3DBallHardLearning.nn
barracuda/mobilenet_v2.nn
bigdl/analytics-zoo_squeezenet-quantize_imagenet_0.1.0.model
caffe/1D_lstm.prototxt
caffe/age_net.caffemodel
caffe/alexnet.prototxt
caffe/AlexNet_SalObjSub_deploy.prototxt
caffe/autocolorize.prototxt
caffe/bvlc_alexnet.caffemodel.zip
caffe/bvlc_caffenet_full_conv.prototxt
caffe/bvlc_alexnet_deploy.prototxt
caffe/bvlc_googlenet.caffemodel
caffe/caffe_array.prototxt
caffe/caffe_invalid_file.caffemodel
caffe/caffe_invalid_semicolon.prototxt
caffe/caffe_semicolon.prototxt
caffe/caffenet.prototxt
caffe/cifar10_full_sigmoid_solver_bn.prototxt
caffe/cityscapes_713_pspnet.prototxt
caffe/conv.prototxt
caffe/deepyeast.caffemodel.zip
caffe/DenseNet_169.prototxt
caffe/deploy_iResNet_ROB.tpl.prototxt
caffe/faster_rcnn_train_test_21cls.pt
caffe/fasterRCNN_AlexNet.prototxt
caffe/fasterRCNN_ResNet.prototxt
caffe/fasterRCNN_VGG.prototxt
caffe/fasterRCNN_ZynqNet.prototxt
caffe/fcn-16s.prototxt
caffe/fcn-8s-pascal-deploy.prototxt
caffe/feat_ext_C3D_examples_imagenet_alexnet_train.prototxt
caffe/googlenet.prototxt
caffe/inceptionv3.prototxt
caffe/inceptionv3_orig.prototxt
caffe/inceptionv4.prototxt
caffe/inceptionv4_resnet.prototxt
caffe/inceptionv4_resnet.prototxt
caffe/lenet_consolidated_solver.prototxt
caffe/lenet.prototxt
caffe/linreg.prototxt
caffe/lstm.prototxt
caffe/mobilenet.caffemodel
caffe/mobilenet_deploy.prototxt
caffe/mobilenet_yolov3_lite_train.prototxt
caffe/mobilenet_yolov3_solver.prototxt
caffe/mobilenet_v2.caffemodel
caffe/mobilenet_v2_deploy.prototxt
caffe/MobileNetSSD_train.prototxt
caffe/MobileNetSSD_train_template.prototxt
caffe/mnist_siamese_solver.prototxt
caffe/0306.pbtxt
caffe/nin.prototxt
caffe/ORION_extended_trainval.prototxt
caffe/panoramic_object_detection_deploy_crop.prototxt.prototxt
caffe/ResNet-18-deploy.prototxt
caffe/ResNet-34.prototxt
caffe/resnet-50.prototxt
caffe/ResNet-50-deploy.prototxt
caffe/ResNet-50_merged.qconv.winograd.cwl.prototxt
caffe/ResNet-152-deploy.prototxt
caffe/resnet-152.prototxt
caffe/seq2seq_train_ep7_tar.prototxt
caffe/se_resnet_50_v1_deploy.prototxt
caffe/segnet_basic_inference.prototxt
caffe/shufflenet_1x_g3_train.prototxt
caffe/squeezenet_v1.1.caffemodel
caffe/sq11b2a_e3.prototxt
caffe/squeezenet.prototxt
caffe/squeezenet_v11.prototxt
caffe/ssd_16nodes_512_batch_train.prototxt
caffe/SSD300.prototxt
caffe/tsn_bn_inception_flow_deploy.prototxt
caffe/vanillaCNN.caffemodel
caffe/vgg-16.prototxt
caffe/VGG_CNN_M_2048_deploy.prototxt
caffe/VGG_VOC0712Plus_SSD_300x300_ft_deploy.prototxt
caffe/YOLO.prototxt
caffe/yolov3_gen.prototext.txt
caffe/yolov3-tiny.prototxt
caffe/yolov3-spp.prototxt
caffe/zynqnet.prototxt
caffe2/bvlc_alexnet/predict_net.pb
caffe2/bvlc_alexnet/init_net.pb
caffe2/bvlc_alexnet/predict_net.pbtxt
caffe2/bvlc_googlenet/predict_net.pb
caffe2/densenet121/predict_net.pb
caffe2/FBNet-A-int8/model.pbtxt
caffe2/generalized_rcnn/net.pbtxt
caffe2/generalized_rcnn/predict_net.pbtxt
caffe2/inception_v2/predict_net.pb
caffe2/lenet/predict_net.pbtxt
caffe2/mask_rcnn_2go/model.pbtxt
caffe2/mobilenet_v2/predict_net.pb
caffe2/mobilenet_v2/predict_net.pb
caffe2/onnx_while/predict_net.pb
caffe2/resnet50/predict_net.pb
caffe2/squeezenet/squeezenet.pb
cambricon/deepsort_4c4b_bgr_270_v140.cambricon
cambricon/SR_face_x3_530x530.cambricon
catboost/iris_model.cbm
catboost/model.cbm
catboost/model.pkl
catboost/numeric_only_model.cbm
circle/ArgMax_001.circle
circle/FullyConnected_002.circle
cntk/01_OneHidden.dnn
cntk/Bean.cntk
cntk/cifar10.pretrained.cmf
cntk/cifar10.ResNet.cmf
cntk/cntkSpeechFF.dnn
cntk/d_I160x160x3CMCMCMCMCMCMC1AS.model
cntk/DRNN.model
cntk/initial_policy_network.dnn
cntk/ResNet20_CIFAR10_DataAug.dnn
cntk/ResNet20_CIFAR10_CNTK.model
cntk/ResNet110_CIFAR10_CNTK.model
cntk/slu.forward.backward.cmf
cntk/slu.forward.cmf
cntk/slu.forward.nobn.cmf
cntk/slu.forward.lookahead.cmf
cntk/tutorial_103b_mnist.model
cntk/tutorial_103c_mnist.model
cntk/tutorial_103d_mnist.model
cntk/tutorial_106a_lstm.model
cntk/VDSR.model
coreml/accumulator_example_state_model.mlpackage.zip
coreml/BERTSQUADFP16.mlmodel
coreml/combined_adpater_models.mlpackage.zip
coreml/DeepLabV3.pb
coreml/DocumentClassification.mlmodel
coreml/EfficientNetB0.mlpackage
coreml/EfficientNetB0.mlpackage.zip
coreml/EnvSceneClassification.mlmodel
coreml/Exermote.mlmodel
coreml/Exermote.pbtxt
coreml/faces_model.mlmodel
coreml/float16.mlmodel
coreml/FNS-Candy.mlmodel
coreml/food.mlmodel
coreml/food_kmeans_1.mlmodel
coreml/food_kmeans_2.mlmodel
coreml/food_kmeans_3.mlmodel
coreml/food_kmeans_4.mlmodel
coreml/food_kmeans_5.mlmodel
coreml/food_kmeans_6.mlmodel
coreml/food_kmeans_7.mlmodel
coreml/food_kmeans_8.mlmodel
coreml/food_kmeans_16.mlmodel
coreml/food_linear_1.mlmodel
coreml/food_linear_2.mlmodel
coreml/food_linear_3.mlmodel
coreml/food_linear_4.mlmodel
coreml/food_linear_5.mlmodel
coreml/food_linear_6.mlmodel
coreml/food_linear_7.mlmodel
coreml/food_linear_8.mlmodel
coreml/food_linear_16.mlmodel
coreml/food_linear_lut_1.mlmodel
coreml/food_linear_lut_2.mlmodel
coreml/food_linear_lut_3.mlmodel
coreml/food_linear_lut_4.mlmodel
coreml/food_linear_lut_5.mlmodel
coreml/food_linear_lut_6.mlmodel
coreml/food_linear_lut_7.mlmodel
coreml/food_linear_lut_8.mlmodel
coreml/food_linear_lut_16.mlmodel
coreml/FrameGRUModel.mlpackage.zip
coreml/GoogLeNetPlaces.mlmodel
coreml/HED_so.mlmodel
coreml/HED_so3.mlmodel
coreml/imdb_lstm.mlmodel
coreml/imdb_bidirectional_lstm.mlmodel
coreml/Inceptionv3.mlmodel
coreml/iris.mlmodel
coreml/LinkedUpdatableTinyDrawingClassifier.mlmodel
coreml/lstm_model.mlpackage.zip
coreml/MessageClassifier.mlmodel
coreml/MNIST.mlmodel
coreml/MNISTClassifier.mlmodel
coreml/MobileNet.mlmodel
coreml/mobilenet_v2_1.4_224.mlmodel
coreml/mobilenet_v2_not_working_netron.mlpackage.zip
coreml/MovieRecommender.mlmodel
coreml/NamesDT.mlmodel
coreml/onehot_simple.mlmodel
coreml/PoseEstimationForMobile.mlmodel
coreml/ProductTagger.mlmodel
coreml/ProgrammingLanguageClassifier.mlmodel
coreml/ReadTheRoom.mlmodel
coreml/SentimentPolarity.mlmodel
coreml/sentiment_model.mlmodel
coreml/simple_activation_quantized_model.mlpackage.zip
coreml/SqueezeNet.mlmodel
Error: 403
```

</details>

I simply cannot download the files.

<details><summary>wget output</summary>

```
beru@beru-System-Product-Name:~/projects/netron$ wget https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNet.mlmodel
--2024-06-16 00:27:02--  https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNet.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::204, 2403:300:a0c:f100::208, 17.253.69.202, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::204|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-06-16 00:27:02 ERROR 403: Forbidden.

beru@beru-System-Product-Name:~/projects/netron$ wget https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNetFP16.mlmodel
--2024-06-16 00:29:02--  https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNetFP16.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::198, 2403:300:a0c:f100::202, 17.253.69.210, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::198|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-06-16 00:29:02 ERROR 403: Forbidden.

beru@beru-System-Product-Name:~/projects/netron$ wget https://docs-assets.developer.a
pple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNetInt8LUT.mlmodel
--2024-06-16 00:29:19--  https://docs-assets.developer.apple.com/coreml/models/Image/ImageClassification/SqueezeNet/SqueezeNetInt8LUT.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::208, 2403:300:a0c:f100::210, 17.253.69.198, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::208|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-06-16 00:29:20 ERROR 403: Forbidden.
```

</details>

**Comment by lutzroeder** [comment]
@beru do you see the error only for these 3 files or does this happen for all files from this domain?

**Comment by beru** [comment]
@lutzroeder 

> do you see the error only for these 3 files or does this happen for all files from this domain?

I only see the error for these 3 files. As of now, I can download other files from the same domain.

<details><summary>wget output</summary>

```
beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/Image/ObjectDetection/YOLOv3Tiny/YOLOv3Tiny.mlmodel
--2024-06-16 08:01:42--  https://docs-assets.developer.apple.com/coreml/models/Image/ObjectDetection/YOLOv3Tiny/YOLOv3Tiny.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::206, 2403:300:a0c:f100::208, 17.253.69.210, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35527626 (34M) [application/octet-stream]
Saving to: ‘YOLOv3Tiny.mlmodel’

YOLOv3Tiny.mlmodel  100%[===================>]  33.88M  44.2MB/s    in 0.8s    

2024-06-16 08:01:43 (44.2 MB/s) - ‘YOLOv3Tiny.mlmodel’ saved [35527626/35527626]

beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/Text/QuestionAnswering/BERT_SQUAD/BERTSQUADFP16.mlmodel
--2024-06-16 08:02:01--  https://docs-assets.developer.apple.com/coreml/models/Text/QuestionAnswering/BERT_SQUAD/BERTSQUADFP16.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::198, 2403:300:a0c:f100::206, 17.253.69.198, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::198|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 217828474 (208M) [application/octet-stream]
Saving to: ‘BERTSQUADFP16.mlmodel’

BERTSQUADFP16.mlmod 100%[===================>] 207.74M  40.3MB/s    in 4.7s    

2024-06-16 08:02:06 (44.3 MB/s) - ‘BERTSQUADFP16.mlmodel’ saved [217828474/217828474]

beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/Image/ImageSegmentation/DeepLabV3/DeepLabV3.mlmodel
--2024-06-16 08:02:14--  https://docs-assets.developer.apple.com/coreml/models/Image/ImageSegmentation/DeepLabV3/DeepLabV3.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::208, 2403:300:a0c:f100::210, 17.253.69.204, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::208|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8636475 (8.2M) [application/octet-stream]
Saving to: ‘DeepLabV3.mlmodel’

DeepLabV3.mlmodel   100%[===================>]   8.24M  39.2MB/s    in 0.2s    

2024-06-16 08:02:15 (39.2 MB/s) - ‘DeepLabV3.mlmodel’ saved [8636475/8636475]

beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/GoogLeNetPlaces.mlmodel
--2024-06-16 08:02:23--  https://docs-assets.developer.apple.com/coreml/models/GoogLeNetPlaces.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::208, 2403:300:a0c:f100::210, 17.253.69.204, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::208|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24754375 (24M) [binary/octet-stream]
Saving to: ‘GoogLeNetPlaces.mlmodel’

GoogLeNetPlaces.mlm 100%[===================>]  23.61M  47.2MB/s    in 0.5s    

2024-06-16 08:02:24 (47.2 MB/s) - ‘GoogLeNetPlaces.mlmodel’ saved [24754375/24754375]

beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/Inceptionv3.mlmodel
--2024-06-16 08:02:35--  https://docs-assets.developer.apple.com/coreml/models/Inceptionv3.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::204, 2403:300:a0c:f100::202, 17.253.69.206, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 94704130 (90M) [binary/octet-stream]
Saving to: ‘Inceptionv3.mlmodel’

Inceptionv3.mlmodel 100%[===================>]  90.32M  54.5MB/s    in 1.7s    

2024-06-16 08:02:37 (54.5 MB/s) - ‘Inceptionv3.mlmodel’ saved [94704130/94704130]

beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/Image/DrawingClassification/MNISTClassifier/MNISTClassifier.mlmodel
--2024-06-16 08:06:59--  https://docs-assets.developer.apple.com/coreml/models/Image/DrawingClassification/MNISTClassifier/MNISTClassifier.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::204, 2403:300:a0c:f100::202, 17.253.69.206, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 395695 (386K) [application/octet-stream]
Saving to: ‘MNISTClassifier.mlmodel’

MNISTClassifier.mlm 100%[===================>] 386.42K  --.-KB/s    in 0.02s   

2024-06-16 08:06:59 (21.4 MB/s) - ‘MNISTClassifier.mlmodel’ saved [395695/395695]

beru@beru-System-Product-Name:~$ wget https://docs-assets.developer.apple.com/coreml/models/MobileNet.mlmodel
--2024-06-16 08:07:09--  https://docs-assets.developer.apple.com/coreml/models/MobileNet.mlmodel
Resolving docs-assets.developer.apple.com (docs-assets.developer.apple.com)... 2403:300:a0c:f100::204, 2403:300:a0c:f100::198, 17.253.69.206, ...
Connecting to docs-assets.developer.apple.com (docs-assets.developer.apple.com)|2403:300:a0c:f100::204|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17136858 (16M) [binary/octet-stream]
Saving to: ‘MobileNet.mlmodel’

MobileNet.mlmodel   100%[===================>]  16.34M  67.2MB/s    in 0.2s    

2024-06-16 08:07:10 (67.2 MB/s) - ‘MobileNet.mlmodel’ saved [17136858/17136858]
```

</details>

**Pull request closed without merging**
