### PR TITLE
bug fix on displaying quantized tensor

### PR DESCRIPTION
**Pull request by Tee0125**
fix typo

### CODE REVIEW

**Comment by lutzroeder** [comment]
Is `QuantisedAsymm8` the same as `quint8` and `QuantisedSymm16` same as `qint16`?`Signed32` seems the same as `int32`?

**Comment by Tee0125** [comment]
here are sample files. (In case of network in ..._q16.armnn, weight tensor is quantized to asymetric 8bit fixed point, bias is quantized to 32bit integer and activation is quantized to symmetric 16bit fixed point) 
 
[samples.zip](https://github.com/lutzroeder/netron/files/3839429/samples.zip)

**Comment by Tee0125** [comment]
and I think, `qint8` should be `quint8`, and `quint16` should be `qint16`

**Comment by lutzroeder** [comment]
#515

**Pull request closed without merging**
