### PR TITLE
Update view.View.scrollTo method

### PR DESCRIPTION
**Pull request by beru**
This PR is opened to address the issue reported in #1352

### CODE REVIEW

**Comment by lutzroeder** [comment]
Would it help to have a buffer for nodes which are close to the visible border? For example, shrink the test rectangle by 10% so elements close to the border get scrolled into the visible area?

**Comment by beru** [comment]
> 1. Would it help to have a border zone for elements which are close to corners of the visible area? For example, shrink the test rectangle by 10% so elements close to the corners also get scrolled into the visible area?

I'm not sure about that. Shall I create a commit to check UX?

> 2. Should elements scroll to center or only move into the visible area?

Centering a clicked node is a bit too much I think. I suppose moving it inside a [safe-area](https://en.wikipedia.org/wiki/Safe_area_%28television%29) will suffice. The size of the safe area can be around 80% or 90%.

If any of the attemps won't satisfy @fdwr, reverting c5868fe92cf2347749238a7bf8326da4bf270679 would be needed.

> 3. Long edges larger than the visible area cause scrolling when clicked. For example og_285 in [gpt2-lm-head-bs-12.onnx](https://github.com/onnx/models/blob/4c46cd00fbdb7cd30b6c1c17ab54f2e1f4f7b177/validated/text/machine_comprehension/gpt2-bs/model/gpt2-lm-head-bs-12.onnx).

Firstly, I'm not really sure if scrolling is necessary when edges are selected. Does it really help? In some cases when lines are very long, clicking them triggers a long scroll and connected nodes that were previously shown tend to go out of the visible area due to the scrolling.

**Comment by beru** [comment]
@lutzroeder @fdwr done updating the code so can you please check new auto scroll behavior is OK?

**Comment by lutzroeder** [comment]
1. Open [candy.onnx](https://raw.githubusercontent.com/Microsoft/Windows-Machine-Learning/master/Samples/FNSCandyStyleTransfer/UWP/cs/Assets/candy.onnx)
2. Open Find sidebar
3. Scroll to bottom and select `scale_B`
4. Scroll to bottom and select `scalePreprocessor`

**Actual:** does not scroll to new location.

**Comment by beru** [comment]
@lutzroeder 

> 4. Scroll to bottom and select scalePreprocessor
> Actual: does not scroll to new location.

Fixed the bug with 19d547ffeaf29f1d127b1851f010b02bee9b0f05 by using `Number.NEGATIVE_INFINITY` instead of `0`. Currently, the change of this PR disregards your recent commit 7b993c63d1a04c806c45aed2eefbb0368b63e753 so a further adjustment might be needed...

This is off-topic but I've noticed that `outputImage` connection of [candy.onnx](https://raw.githubusercontent.com/Microsoft/Windows-Machine-Learning/master/Samples/FNSCandyStyleTransfer/UWP/cs/Assets/candy.onnx) isn't shown in the FIND sidebar list.

**Comment by lutzroeder** [comment]
Regressed #1356

Open [alexnet.zip.pth](https://github.com/lutzroeder/netron/files/6096607/alexnet.zip.pth.zip).

Actual: initial positioning shows center of node
Expected: initial positioning should show top of node

**Comment by beru** [comment]
> Regressed https://github.com/lutzroeder/netron/issues/1356

Honestly, it's difficult to change auto scroll behavior while keeping #1356.

**Pull request closed without merging**
