### PR TITLE
support for tf func

### PR DESCRIPTION
**Pull request by zvika-adler**
I made the relevant chnages for tf. I didn't find any other formats that use func as a type, so I changed it it the viewer as well. If i am wrong, let me know please.

### CODE REVIEW

**Comment by zvika-adler** [comment]
It looks like you overrode all my changes and they are not there anymore.
Is there any problem with my solution?
It should fix https://github.com/lutzroeder/netron/issues/895
Thanks

**Comment by lutzroeder** [comment]
@zvika-adler trying to find an approach that works for all formats. The general case of nested object graphs likely will require a different UI.

**Comment by zvika-adler** [comment]
Do I need to do something to make it progress?

**Comment by zvika-adler** [comment]
I see that it is still not merged and fixed with the other formats. Is it something I can help or it may take longer than expected? @lutzroeder

**Comment by DoDoENT** [comment]
I've built the app from your branch and I can confirm it works correctly for me.

**Comment by DoDoENT** [comment]
I've added a [simple hack to allow visualizing tensors within functions](https://github.com/microblink/netron/commit/adcb74378940dcac1b16291e2bbcc6451fdbc610). Not a pretty, but works for my case (it's still better than not seeing anything).

**Pull request closed without merging**
