### PR TITLE
Enable toggling Full Screen

### PR DESCRIPTION
**Pull request by beru**
#1085

### CODE REVIEW

**Comment by lutzroeder** [comment]
@beru what specific issue is this addressing and can it be accomplished without adding another menu item? 

For example, on macOS full screen is hidden in the top left menu:

image

**Comment by beru** [comment]
> @beru what specific issue is this addressing and can it be accomplished without adding another menu item?

I'vce opened #1085 to accommodate the request.

Without adding another menu item would be possible. But to do so, there needs to be a way to go back from fullscreen without using a keyboard. Otherwise, some users might complain they had to restart/shutdown their computers to exit from Netron.

**Comment by beru** [comment]
@lutzroeder I've just installed Version 6.8.4 and checked Full Screen toggling.

-----

Before pressing F11 key.

image

After pressing F11 key, the window is maximized and switched to Full Screen but Minimize/Mazimize/Close icons are still shown. They shouldn't appear when the window is in Full Screen.

image

Pressing F11 key again to go back from Full Screen. Oddly, Minimize/Mazimize/Close icons are hidden.

image

---------

To prevent the above weird behavour, please check what I did in #1084 

https://github.com/beru/netron/blob/9c730f0e13ba6a70911fd5c6f4a2bba5296b713c/source/app.js#L822-L835

**Comment by beru** [comment]
I've confirmed that the problem has fone with the recent commit (c4f2cea932af1a28028af01fbfb7912117d595fd), thank you.

**Comment by beru** [comment]
@lutzroeder While Netron is running, Other applications such as VSCode, Microsoft Edge don't react to F11 key for toggling Full Screen.

**Pull request closed without merging**
