### PR TITLE
Re-add function list in graph sidebar for TF

### PR DESCRIPTION
**Pull request by TomWildenhain-Microsoft**

### CODE REVIEW

**Comment by lutzroeder** [comment]
See #784. The right way to resolve this would be supporting signatures?

**Comment by TomWildenhain-Microsoft** [comment]
Supporting signatures would be nice, but I think random access to subgraphs by name is useful regardless.  Keep in mind that TF isn't a recursive graph structure; it is set of function names mapped to graphs, which can call each other.  

Graphs for initializers would be inaccessible even if signatures were implemented.

**Comment by lutzroeder** [comment]
Yes, this requires some exploring what the right design should be. Mixing functions and graphs into a dropdown is likely not the right design.

**Comment by TomWildenhain-Microsoft** [comment]
No problem.  I'll just stick to an old version of Netron for now when viewing saved models.

**Pull request closed without merging**
