### PR TITLE
modify default tensorType of MSLite

### PR DESCRIPTION
**Pull request by YvetteLaw**
fix a bug

### CODE REVIEW

**Comment by lutzroeder** [comment]
What exactly is the bug and is there a repro? The code should throw for an unknown data type and the specific issue should get fixed instead of silently catching all failures.

**Comment by YvetteLaw** [comment]
> What exactly is the bug and is there a repro? The code should throw for an unknown data type and the specific issue should get fixed instead of silently catching all failures.

https://github.com/mindspore-ai/mindspore/blob/master/mindspore/core/ir/dtype/type_id.h

**Comment by lutzroeder** [comment]
The right approach is to show a useful name and fail if an unknown or new one is added. If the value is saved to a persistent model it has some meaning and users might want to know about that instead of seeing a `?`. Some of these do not seem to be data types but they are stored as data types -- is that a design that should be fixed? Is there a sample model file to reproduce the issue you are trying to fix?

**Comment by YvetteLaw** [comment]
> The right approach is to show a useful name and fail if an unknown or new one is added. If the value is saved to a persistent model it has some meaning and users might want to know about that instead of seeing a `?`. Some of these do not seem to be data types but they are stored as data types -- is that a design that should be fixed? Is there a sample model file to reproduce the issue for this fix?

I've modified them with their name. 

"Some of these do not seem to be data types but they are stored as data types -- is that a design that should be fixed? "-----It's our design.

**Pull request closed without merging**
