### PR TITLE
DaVinci : fix svp format support

### PR DESCRIPTION
**Pull request by wujunliang00**
Hi, I'm trying to support DaVinci model(.om) svp format in netron, can u help me review the code and merge the new feature into the main branch? 
thanks!

the sample models:
[resnet50_issue_svp.zip](https://github.com/lutzroeder/netron/files/9813559/resnet50_issue_svp.zip)
Also,  this request can be solved https://github.com/lutzroeder/netron/issues/993

### CODE REVIEW

**Comment by lutzroeder** [comment]
@wujunliang00 
* Why is there a different format, should to `.proto` files for both formats get merged and unified?
* The code in `om-proto-svp.js` looks handed edited. Add the `.proto` in `./tools/om` and regenerate the file.
* All `.proto` definitions should get merged into `om-proto.js` .

**Review by lutzroeder — CHANGES_REQUESTED** [review]
@wujunliang00

* Why is there a different format, should the `.proto` files for both formats get merged and unified?
* The code in `om-proto-svp.js` looks handed-edited. Add the `.proto` in `./tools/om` and regenerate the file.
* The `.proto` definitions for `om.js` should be in `om-proto.js`.
* Who will maintain and support this change going forward?

**Comment by wujunliang00** [comment]
> @wujunliang00
> 
> * Why is there a different format, should the `.proto` files for both formats get merged and unified?
> * The code in `om-proto-svp.js` looks handed-edited. Add the `.proto` in `./tools/om` and regenerate the file.
> * The `.proto` definitions for `om.js` should be in `om-proto.js`.
> * Who will maintain and support this change going forward?

* Since this structure is a model on the deployment side of HiAi, in order to make the performance faster during deployment, it adopts its own parsing, which makes it impossible to parse in the form of protobuf.
* Due to the use of another parsing method, it is not compatible with `om-proto`, sorry~~ , I don't have the ability to be compatible on `om.proto`.
*  HiAscend maintains and support this change going forward, please refer to this: https://www.hiascend.com/en/
* The OM model of 'PICO' is generally deployed on platforms with low computing power.

**Comment by lutzroeder** [comment]
@wujunliang00

* Calling the `om-proto-svp` is misleading if it not using Protocol Buffers
* What does the `svp` moniker stand for?
* Is there an overview of the different DaVinci OM formats?
* Please add support for weight initializers

**Comment by wujunliang00** [comment]
> @wujunliang00
> 
> * What does the `svp` moniker stand for?
> * Is there an overview of the different DaVinci OM formats?
> * Please add support for weight initializers

1.  svp：smart vision pico of om
2. At present, I am adapting to the om of svp, and there are other types for DaVinci OM, but they are all in the direct proto format, and do not need original parsing like me
3. weight initializers will be adapted in the future, and it is not supported for the time being.

**Comment by lutzroeder** [comment]
@wujunliang00 is there a reason to not add weight initializers now? It is the main reason to keep the feature disabled.

**Comment by wujunliang00** [comment]
@lutzroeder 

Because the weight data is placed in the instructions issued by the hardware, it is convenient to directly deploy the om file on the hardware, but it is very difficult to parse natively, because the weight data has been converted into instructions and stored in om

**Pull request closed without merging**
