### PR TITLE
add subGraph function to MSLite

### PR DESCRIPTION
**Pull request by YvetteLaw**
We have added the subGraph function to MSLite. Please merge this PR.

### CODE REVIEW

**Comment by lutzroeder** [comment]
@YvetteLaw can you add a sample model in `./test/models.json`?

**Comment by YvetteLaw** [comment]
> @YvetteLaw can you add a sample model in `./test/models.json`?

Please see the model 'control_flow_ut_while_0122.ms'

**Comment by lutzroeder** [comment]
This PR seems to break compatibility with the 1.0 format. Also, please add back a 1.0 test file for regression testing. It is not acceptable that the format keeps changing and users will have a bad experience when loading existing models. If this cannot be resolved maybe MSLite support should be removed as the format is not stable.

**Comment by YvetteLaw** [comment]
> This PR seems to break compatibility with the 1.0 format? Please add back a 1.0 test file for regression testing. It is not acceptable that the format keeps changing and users will have a bad experience when loading existing models. If this cannot be resolved maybe MSLite support should be removed as the format is not stable.

I've added test models with 1.0.0 format

**Comment by lutzroeder** [comment]
`subgraph === []` does not work .

**Pull request closed without merging**
