### PR TITLE
update darknet-metadata.json

### PR DESCRIPTION
**Pull request by HagegeR**
added missing net option, some descriptions, and some attributes type.

can you please help me on the TODO's and in the "from" attribute (a kind of routing) ?

### CODE REVIEW

**Comment by lutzroeder** [comment]
@HagegeR can you update the PR to latest? `boolean` is now handled as `int32` in `master` and `from` is handled for  `scale_channels`.

**Comment by HagegeR** [comment]
done, what about shortcut and sam? is from supported there too?

also I don't know why but it's as if I changed all the files although the files are the same (21 file change when it's only 2)

**Comment by lutzroeder** [comment]
Can you validate the change? `node ./test/test.js darknet` fails with errors.

**Comment by HagegeR** [comment]
can I see the errors?

**Comment by lutzroeder** [comment]
Already fixed and manually merged to ‘master’.

**Pull request closed without merging**
